### ISSUE TITLE
Unable to install the MPIBenchmarks.jl

### ISSUE THREAD

**Issue by binhudakhalid** [JuliaParallel/MPIBenchmarks.jl#3]
Hi,

I was trying to install MPIBenchmarks.jl by using Julia REPL. But getting an error, stating that the version of MPI.jl should be 0.20. And the latest version for mpi.jl is v0.19.2.

![image](https://user-images.githubusercontent.com/9871507/190506915-900b4905-91b0-4e4f-b987-3dcf1278dc4c.png)

Update: I did install MPIBenchmarks.jl by changing the value in MPIBenchmarks.jl/Project.toml to MPI = "0.20, 0.19".
But now getting this error
![image](https://user-images.githubusercontent.com/9871507/190520954-5c2f4229-f257-4cdb-a99a-ac0e51d7888e.png)

![image](https://user-images.githubusercontent.com/9871507/190521019-f194c111-7270-4b11-8857-336f458f23db.png)

**Comment by giordano** [comment]
Hi, thanks for trying this package out!  You haven't done anything wrong, but this package at the moment requires the development version of `MPI.jl` (v0.20.0), which you can install with `]add MPI#master`.  This is mainly because I developed this package for testing on Fugaku (see https://github.com/giordano/julia-on-fugaku/ and the paper https://arxiv.org/abs/2207.12762), where `MPI.jl` v0.20.0 is considerably easier to set up than v0.19.
